export enum MessageTypes  {
    STATE_CHANGE = "STATE_CHANGE",
    DOWNLOAD = "DOWNLOAD",
    GET_STATE = "GET_STATE",
    STORY_SEEN = "STORY_SEEN",
    INSTAGRAM_REQUEST = "INSTAGRAM_REQUEST",
    INSTAGRAM_PROFILE = "INSTAGRAM_PROFILE",
    OPEN_TAB = "OPEN_TAB",
    INSTAGRAM_STORY_SEEN = "INSTAGRAM_STORY_SEEN",
    INSTA_STORY_CACHE = "INSTA_STORY_CACHE",
    GET_FACEBOOK_PROFILE = "GET_FACEBOOK_PROFILE",
    GET_FACEBOOK_ALBUMS = "GET_FACEBOOK_ALBUMS",
}